import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from './components/navigation';
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata: Metadata = {
  title: "Suggestions App",
  description: "Generated by create next app - this is a audience suggestions web app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en" className="antialiased light" style={{ colorScheme: 'light'}}>
      <UserProvider>
        <body className="font-sans">
          <div className="isolate">
          <Navigation />
          {children}
          </div>
        </body>
      </UserProvider>
      </html>
  );
}
